PORT_LOBBY_DEFAULT = 1956
PORT_ROOM_DEFAULT = 1955

MESSAGE_PLAYER_CONNECTED = 0
MESSAGE_PLAYER_DISCONNECTED = 1
MESSAGE_PLAYER_MOVED = 2
MESSAGE_REQUEST_SERVER_STATUS = 3
MESSAGE_SERVER_STATUS = 4
MESSAGE_PLAYER_JOIN_ROOMSERVER = 5